// Generated by Kiro AI
// Prompt: Implement the button separation feature: Replace the existing Generate Code & PR button with two separate buttons - Generate Code and Create PR. Add proper event handlers and modal dialogs.
// Generated at: 2025-12-14T12:57:08.078Z

Implement the button separation feature: Replace the existing Generate Code & PR button with two separate buttons - !> Implement the button separation feature: Replace the existing Generate Code & PR button with two separate buttons - G
enerate Code and Create PR. Add proper event handlers and modal dialogs.[

[                                        [                                                                                                  I'll create the following file: /home/ec2-user/aipm/button-replacement.js (using tool: write)

+      1: // Replace Generate Code & PR button with separate buttons
+      2: function replaceButtons() {
+      3:   document.querySelectorAll('.generate-code-pr-btn').forEach(btn => {
+      4:     const parent = btn.parentElement;
+      5:     
+      6:     const generateBtn = document.createElement('button');
+      7:     generateBtn.textContent = 'Generate Code';
+      8:     generateBtn.className = 'generate-code-btn';
+      9:     generateBtn.onclick = () => showGenerateModal(btn.dataset.taskId);
+     10:     
+     11:     const prBtn = document.createElement('button');
+     12:     prBtn.textContent = 'Create PR';
+     13:     prBtn.className = 'create-pr-btn';
+     14:     prBtn.onclick = () => showPRModal(btn.dataset.taskId);
+     15:     
+     16:     parent.insertBefore(generateBtn, btn);
+     17:     parent.insertBefore(prBtn, btn);
+     18:     btn.remove();
+     19:   });
+     20: }
+     21: 
+     22: function showGenerateModal(taskId) {
+     23:   const modal = createModal('Generate Code', `
+     24:     <input type="text" id="task-title" placeholder="Task Title" required>
+     25:     <textarea id="objective" placeholder="Objective" required></textarea>
+     26:     <textarea id="constraints" placeholder="Constraints"></textarea>
+     27:     <button onclick="generateCode('${taskId}')">Generate</button>
+     28:     <button onclick="closeModal()">Cancel</button>
+     29:   `);
+     30:   document.body.appendChild(modal);
+     31: }
+     32: 
+     33: function showPRModal(taskId) {
+     34:   const modal = createModal('Create PR', `
+     35:     <input type="url" id="repo-url" placeholder="Repository URL" required>
+     36:     <input type="text" id="branch" placeholder="Branch Name" required>
+     37:     <input type="text" id="pr-title" placeholder="PR Title" required>
+     38:     <textarea id="description" placeholder="Description"></textarea>
+     39:     <button onclick="createPR('${taskId}')">Create PR</button>
+     40:     <button onclick="closeModal()">Cancel</button>
+     41:   `);
+     42:   document.body.appendChild(modal);
+     43: }
+     44: 
+     45: function createModal(title, content) {
+     46:   const modal = document.createElement('div');
+     47:   modal.className = 'modal';
+     48:   modal.innerHTML = `
+     49:     <div class="modal-content">
+     50:       <h3>${title}</h3>
+     51:       ${content}
+     52:     </div>
+     53:   `;
+     54:   return modal;
+     55: }
+     56: 
+     57: async function generateCode(taskId) {
+     58:   const data = {
+     59:     taskId,
+     60:     title: document.getElementById('task-title').value,
+     61:     objective: document.getElementById('objective').value,
+     62:     constraints: document.getElementById('constraints').value
+     63:   };
+     64:   
+     65:   try {
+     66:     await fetch('/api/generate-code', {
+     67:       method: 'POST',
+     68:       headers: { 'Content-Type': 'application/json' },
+     69:       body: JSON.stringify(data)
+     70:     });
+     71:     closeModal();
+     72:     alert('Code generation started');
+     73:   } catch (e) {
+     74:     alert('Error generating code');
+     75:   }
+     76: }
+     77: 
+     78: async function createPR(taskId) {
+     79:   const data = {
+     80:     taskId,
+     81:     repoUrl: document.getElementById('repo-url').value,
+     82:     branch: document.getElementById('branch').value,
+     83:     title: document.getElementById('pr-title').value,
+     84:     description: document.getElementById('description').value
+     85:   };
+     86:   
+     87:   try {
+     88:     await fetch('/api/create-pr', {
+     89:       method: 'POST',
+     90:       headers: { 'Content-Type': 'application/json' },
+     91:       body: JSON.stringify(data)
+     92:     });
+     93:     closeModal();
+     94:     alert('PR created successfully');
+     95:   } catch (e) {
+     96:     alert('Error creating PR');
+     97:   }
+     98: }
+     99: 
+    100: function closeModal() {
+    101:   document.querySelector('.modal')?.remove();
+    102: }
+    103: 
+    104: document.addEventListener('DOMContentLoaded', replaceButtons);

Creating: /home/ec2-user/aipm/button-replacement.js
 - Completed in 0.0s

[                                                > Created button replacement feature with separate Generate Code and Create PR buttons, including modal dialogs and 
event handlers in /home/ec2-user/aipm/button-replacement.js.
 ▸ Time: 15s

[[!> [3C