#!/bin/bash
# Kiro worker - polls DynamoDB queue and generates code

set -e

QUEUE_TABLE="aipm-amazon-q-queue"
REGION="us-east-1"

echo "🤖 Kiro worker started"
echo "Polling queue: $QUEUE_TABLE"

while true; do
  # Get pending tasks from DynamoDB
  TASKS=$(aws dynamodb scan \
    --table-name "$QUEUE_TABLE" \
    --filter-expression "#status = :pending" \
    --expression-attribute-names '{"#status":"status"}' \
    --expression-attribute-values '{":pending":{"S":"pending"}}' \
    --region "$REGION" \
    --output json)
  
  TASK_COUNT=$(echo "$TASKS" | jq '.Items | length')
  
  if [ "$TASK_COUNT" -gt 0 ]; then
    echo "📋 Found $TASK_COUNT pending task(s)"
    
    # Process each task
    echo "$TASKS" | jq -c '.Items[]' | while read -r task; do
      TASK_ID=$(echo "$task" | jq -r '.id.S')
      TITLE=$(echo "$task" | jq -r '.title.S')
      DETAILS=$(echo "$task" | jq -r '.details.S')
      BRANCH=$(echo "$task" | jq -r '.branch.S // "develop"')
      
      echo "🔨 Processing: $TASK_ID - $TITLE"
      
      # Update status to processing
      aws dynamodb update-item \
        --table-name "$QUEUE_TABLE" \
        --key "{\"id\":{\"S\":\"$TASK_ID\"}}" \
        --update-expression "SET #status = :processing" \
        --expression-attribute-names '{"#status":"status"}' \
        --expression-attribute-values '{":processing":{"S":"processing"}}' \
        --region "$REGION"
      
      # Checkout branch
      git fetch origin
      git checkout "$BRANCH"
      git pull origin "$BRANCH"
      
      # Use Kiro to generate code
      TASK_DESC="$TITLE

$DETAILS"
      
      echo "💬 Asking Kiro: $TASK_DESC"
      kiro-cli chat "$TASK_DESC" --non-interactive || true
      
      # Check if Kiro made changes
      if [ -n "$(git status --porcelain)" ]; then
        echo "✅ Kiro generated changes"
        
        # Create new branch
        NEW_BRANCH="kiro/$TASK_ID"
        git checkout -b "$NEW_BRANCH"
        
        # Commit changes
        git add .
        git commit -m "feat: $TITLE

Generated by Kiro CLI

Task ID: $TASK_ID
$DETAILS"
        
        # Push branch
        git push origin "$NEW_BRANCH"
        
        # Create PR
        gh pr create \
          --base "$BRANCH" \
          --head "$NEW_BRANCH" \
          --title "🤖 Kiro: $TITLE" \
          --body "## Kiro Generated Code

**Task:** $TITLE

$DETAILS

**Task ID:** $TASK_ID

### Review Required
- [ ] Code quality check
- [ ] Test the changes
- [ ] Merge when ready"
        
        # Update status to complete
        aws dynamodb update-item \
          --table-name "$QUEUE_TABLE" \
          --key "{\"id\":{\"S\":\"$TASK_ID\"}}" \
          --update-expression "SET #status = :complete" \
          --expression-attribute-names '{"#status":"status"}' \
          --expression-attribute-values '{":complete":{"S":"complete"}}' \
          --region "$REGION"
        
        echo "✅ PR created for $TASK_ID"
      else
        echo "⚠️ No changes generated"
        
        # Update status to failed
        aws dynamodb update-item \
          --table-name "$QUEUE_TABLE" \
          --key "{\"id\":{\"S\":\"$TASK_ID\"}}" \
          --update-expression "SET #status = :failed, errorMessage = :error" \
          --expression-attribute-names '{"#status":"status"}' \
          --expression-attribute-values '{":failed":{"S":"failed"},":error":{"S":"No code generated"}}' \
          --region "$REGION"
      fi
      
      # Return to original branch
      git checkout "$BRANCH"
    done
  else
    echo "💤 No pending tasks"
  fi
  
  # Wait before next poll
  sleep 30
done
