#!/bin/bash
set -e

TASK="$1"
if [ -z "$TASK" ]; then
  echo "Usage: ./q-auto-generate.sh \"task description\""
  exit 1
fi

BRANCH="amazonq/$(date +%s)"

echo "🤖 Amazon Q Automated Code Generation"
echo "Task: $TASK"
echo ""

# Create branch
git checkout develop
git pull origin develop
git checkout -b "$BRANCH"

# Use Amazon Q to generate code automatically
echo "Generating code with Amazon Q..."

# Create prompt file
cat > /tmp/q-prompt.txt << EOF
Generate code for this task: $TASK

Requirements:
- Create or modify files as needed
- Follow existing code style
- Add comments
- Make it production-ready

Provide the complete file contents.
EOF

# Use kiro-cli to generate code
kiro-cli chat --non-interactive < /tmp/q-prompt.txt > /tmp/q-output.txt 2>&1 || true

# Parse output and create files
# (Amazon Q output will contain file paths and code)
echo "Code generated. Review output:"
cat /tmp/q-output.txt

# Commit all changes
git add -A
if git diff --staged --quiet; then
  echo "No changes generated. Please review the task."
  exit 1
fi

git commit -m "feat: $TASK (Amazon Q generated)"
git push origin "$BRANCH"

# Create PR
gh pr create \
  --base develop \
  --head "$BRANCH" \
  --title "🤖 Amazon Q: $TASK" \
  --body "## Amazon Q Generated Code

**Task:** $TASK

### Generated Files
\`\`\`
$(git diff --name-only develop.."$BRANCH")
\`\`\`

### ⚠️ Review Required
- [ ] Test the changes
- [ ] Verify code quality
- [ ] Check for security issues

**Auto-generated by:** Amazon Q CLI"

echo ""
echo "✅ PR created: https://github.com/demian7575/aipm/pulls"
