#!/bin/bash
set -e

# Amazon Q Local Code Generation and PR Creation
# Usage: ./q-generate-and-pr.sh "task description"

TASK="$1"
if [ -z "$TASK" ]; then
  echo "Usage: ./q-generate-and-pr.sh \"task description\""
  exit 1
fi

BRANCH="amazonq/$(date +%s)"

echo "🤖 Amazon Q Code Generation Workflow"
echo "Task: $TASK"
echo "Branch: $BRANCH"
echo ""

# 1. Create branch
echo "📌 Creating branch..."
git checkout develop
git pull origin develop
git checkout -b "$BRANCH"

# 2. Use Amazon Q to generate code
echo ""
echo "🤖 Use Amazon Q (Kiro) to generate code:"
echo "   1. Open this in your IDE"
echo "   2. Use Amazon Q chat"
echo "   3. Describe: $TASK"
echo "   4. Let Q generate the code"
echo "   5. Review and save the files"
echo ""
read -p "Press Enter when code is generated and saved..."

# 3. Commit changes
echo ""
echo "📝 Committing changes..."
git add -A
git commit -m "feat: $TASK (Amazon Q generated)"

# 4. Push branch
echo "📤 Pushing to GitHub..."
git push origin "$BRANCH"

# 5. Create PR
echo "🔀 Creating PR..."
gh pr create \
  --base develop \
  --head "$BRANCH" \
  --title "🤖 Amazon Q: $TASK" \
  --body "## Amazon Q Generated Code

**Task:** $TASK

### ⚠️ Human Review Required
- [ ] Code quality check
- [ ] Test the changes
- [ ] Update if needed

**Generated by:** Amazon Q (Kiro CLI)
**Branch:** $BRANCH"

echo ""
echo "✅ Done! PR created."
echo "View PRs: https://github.com/demian7575/aipm/pulls"
