#!/bin/bash
set -e

echo "🚀 Amazon Q Worker starting..."

# Get task from environment (passed by ECS)
TASK_ID="${TASK_ID}"
TASK_TITLE="${TASK_TITLE}"
TASK_DETAILS="${TASK_DETAILS}"
BRANCH_NAME="${BRANCH_NAME}"

if [ -z "$TASK_ID" ]; then
  echo "❌ No task provided"
  exit 1
fi

echo "📋 Processing task: $TASK_ID - $TASK_TITLE"

# Update task status to processing
aws dynamodb update-item \
  --table-name "$DYNAMODB_TABLE" \
  --key "{\"id\":{\"S\":\"$TASK_ID\"}}" \
  --update-expression "SET #s = :status" \
  --expression-attribute-names '{"#s":"status"}' \
  --expression-attribute-values '{":status":{"S":"processing"}}' \
  --region "$AWS_REGION"

# Clone repository
git clone "https://${GITHUB_TOKEN}@github.com/${GITHUB_OWNER}/${GITHUB_REPO}.git" repo
cd repo

# Create branch
git checkout -b "$BRANCH_NAME"

# Try Amazon Q with IAM auth
echo "🤖 Attempting Amazon Q code generation..."
if kiro-cli chat --non-interactive --trust-all-tools <<EOF
$TASK_DETAILS

Please implement this feature following the existing code patterns. Commit your changes when done.
EOF
then
  echo "✅ Amazon Q generated code successfully"
  
  # Check if changes were made
  if git diff --quiet && git diff --cached --quiet; then
    echo "⚠️ No changes detected, creating placeholder"
    CREATE_PLACEHOLDER=true
  else
    echo "✅ Changes detected, committing..."
    git add -A
    git commit -m "feat: $TASK_TITLE

Generated by Amazon Q via AIPM ECS Worker.

Task ID: $TASK_ID
Details: $TASK_DETAILS" || true
    CREATE_PLACEHOLDER=false
  fi
else
  echo "⚠️ Amazon Q failed, creating placeholder"
  CREATE_PLACEHOLDER=true
fi

# Create placeholder if needed
if [ "$CREATE_PLACEHOLDER" = "true" ]; then
  cat > TASK_${TASK_ID}.md <<EOF
# Task: $TASK_TITLE

## Details
$TASK_DETAILS

## Implementation Notes
This PR was automatically created by AIPM ECS Worker.

## Status
Ready for implementation

## Next Steps
1. Review task requirements
2. Implement the feature
3. Add tests
4. Update documentation
EOF

git add TASK_${TASK_ID}.md
git commit -m "feat: $TASK_TITLE

Auto-generated task placeholder by AIPM ECS Worker.

Task ID: $TASK_ID
Details: $TASK_DETAILS"
fi

# Push changes
git push origin "$BRANCH_NAME"

# Create PR
PR_RESPONSE=$(curl -s -X POST \
  -H "Authorization: token $GITHUB_TOKEN" \
  -H "Content-Type: application/json" \
  "https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}/pulls" \
  -d "{
    \"title\":\"feat: $TASK_TITLE\",
    \"body\":\"$TASK_DETAILS\\n\\nAuto-generated by AIPM ECS Worker\\nTask ID: $TASK_ID\",
    \"head\":\"$BRANCH_NAME\",
    \"base\":\"main\"
  }")

# Extract PR number without jq (using grep and sed)
PR_NUMBER=$(echo "$PR_RESPONSE" | grep -o '"number":[0-9]*' | head -1 | sed 's/"number"://')

if [ -n "$PR_NUMBER" ] && [ "$PR_NUMBER" -gt 0 ] 2>/dev/null; then
  echo "✅ PR #$PR_NUMBER created"
  
  # Update task status to complete
  aws dynamodb update-item \
    --table-name "$DYNAMODB_TABLE" \
    --key "{\"id\":{\"S\":\"$TASK_ID\"}}" \
    --update-expression "SET #s = :status, prNumber = :pr" \
    --expression-attribute-names '{"#s":"status"}' \
    --expression-attribute-values "{\":status\":{\"S\":\"complete\"},\":pr\":{\"N\":\"$PR_NUMBER\"}}" \
    --region "$AWS_REGION"
else
  echo "❌ PR creation failed"
  echo "$PR_RESPONSE"
  
  # Update task status to failed
  aws dynamodb update-item \
    --table-name "$DYNAMODB_TABLE" \
    --key "{\"id\":{\"S\":\"$TASK_ID\"}}" \
    --update-expression "SET #s = :status" \
    --expression-attribute-names '{"#s":"status"}' \
    --expression-attribute-values '{":status":{"S":"failed"}}' \
    --region "$AWS_REGION"
  
  exit 1
fi

echo "🎉 Task complete!"
