#!/bin/bash
set -e

echo "☁️  Rebuilding Docker image in AWS CloudShell..."
echo ""
echo "📋 Instructions:"
echo "1. Open AWS CloudShell: https://console.aws.amazon.com/cloudshell"
echo "2. Run these commands:"
echo ""
echo "# Clone the repo"
echo "git clone https://github.com/demian7575/aipm.git"
echo "cd aipm"
echo ""
echo "# Build and push"
echo "REGION=us-east-1"
echo "ACCOUNT_ID=\$(aws sts get-caller-identity --query Account --output text)"
echo "REPO_NAME=aipm-q-worker"
echo "ECR_URI=\${ACCOUNT_ID}.dkr.ecr.\${REGION}.amazonaws.com/\${REPO_NAME}"
echo ""
echo "# Login to ECR"
echo "aws ecr get-login-password --region \$REGION | docker login --username AWS --password-stdin \$ECR_URI"
echo ""
echo "# Build image"
echo "docker build -f Dockerfile.q-worker -t \$REPO_NAME:latest ."
echo ""
echo "# Tag and push"
echo "docker tag \$REPO_NAME:latest \$ECR_URI:latest"
echo "docker push \$ECR_URI:latest"
echo ""
echo "✅ Done! New ECS tasks will use the updated image."
