AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  AipmApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda.handler
      Runtime: nodejs18.x
      Environment:
        Variables:
          AIPM_DATA_DIR: /tmp/aipm/data
          AIPM_UPLOAD_DIR: /tmp/aipm/uploads
          AIPM_DISABLE_SQLITE_MIRROR: '1'
          AI_PM_FORCE_JSON_DB: '1'
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        RootEvent:
          Type: Api
          Properties:
            Path: /
            Method: ANY

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
