#!/bin/bash
# CloudShell script to generate code with Amazon Q and create PR
# Usage: ./cloudshell-generate.sh

set -e

echo "🔍 Checking for pending code generation tasks..."

# Get task from API
TASK_JSON=$(curl -s "https://wk6h5fkqk9.execute-api.us-east-1.amazonaws.com/prod/api/code-generation-queue/next")

if [ "$TASK_JSON" = "null" ] || [ -z "$TASK_JSON" ]; then
  echo "✅ No pending tasks"
  exit 0
fi

TASK_TITLE=$(echo "$TASK_JSON" | jq -r '.taskTitle')
TASK_DETAILS=$(echo "$TASK_JSON" | jq -r '.taskDetails')
BRANCH_NAME=$(echo "$TASK_JSON" | jq -r '.branchName')
TASK_ID=$(echo "$TASK_JSON" | jq -r '.id')

echo "📋 Task: $TASK_TITLE"
echo "🌿 Branch: $BRANCH_NAME"
echo ""

cd /home/cloudshell-user/aipm

# Update repo
git fetch origin main
git checkout main
git pull origin main

# Create branch
git checkout -b "$BRANCH_NAME" 2>/dev/null || git checkout "$BRANCH_NAME"

# Generate code with Amazon Q (full repo context)
echo "🤖 Amazon Q analyzing repository..."
q chat "Implement: $TASK_TITLE. Requirements: $TASK_DETAILS. Follow existing patterns in this AIPM repository. Generate minimal, working code." --non-interactive

# Commit and push
git add -A
if git diff --staged --quiet; then
  echo "⚠️  No changes generated"
  curl -X POST "https://wk6h5fkqk9.execute-api.us-east-1.amazonaws.com/prod/api/code-generation-queue/$TASK_ID/complete" \
    -H "Content-Type: application/json" \
    -d '{"status":"failed","error":"No code generated"}'
  exit 1
fi

git config user.name "Amazon Q"
git config user.email "amazonq@aipm.dev"
git commit -m "feat: $TASK_TITLE"
git push -u origin "$BRANCH_NAME"

# Create PR
gh pr create \
  --title "$TASK_TITLE" \
  --body "## 🤖 AI-Generated by Amazon Q

**Full repository context used**

## 📋 Requirements
$TASK_DETAILS

## ✅ Generated with Amazon Q CLI
Code generated with full understanding of AIPM codebase structure and patterns.

## 🚀 Testing
- Development: http://aipm-dev-frontend-hosting.s3-website-us-east-1.amazonaws.com
- Production: http://aipm-static-hosting-demo.s3-website-us-east-1.amazonaws.com" \
  --base main \
  --head "$BRANCH_NAME"

PR_NUMBER=$(gh pr view "$BRANCH_NAME" --json number -q '.number')

# Mark task complete
curl -X POST "https://wk6h5fkqk9.execute-api.us-east-1.amazonaws.com/prod/api/code-generation-queue/$TASK_ID/complete" \
  -H "Content-Type: application/json" \
  -d "{\"status\":\"success\",\"prNumber\":$PR_NUMBER}"

echo "✅ PR #$PR_NUMBER created: https://github.com/demian7575/aipm/pull/$PR_NUMBER"
