#!/bin/bash
# Auto-generated Phase 4 tests from acceptance tests
# DO NOT EDIT MANUALLY - Generated by generate-phase4-from-acceptance-tests.sh

set -e

TEST_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$TEST_SCRIPT_DIR/../utilities/load-env-config.sh" "${TARGET_ENV:-prod}"
source "$TEST_SCRIPT_DIR/test-library.sh"

PASSED=0
FAILED=0
SKIPPED=0
PHASE="phase4-generated"

echo "🧪 Phase 4: Generated Tests from Acceptance Tests"
echo "=================================================="
echo "Run ID: $TEST_RUN_ID"
echo ""


# Test 8: AT-CS-API-L4-007-02: Delete dependency (Story #1107)
echo "Test 8: AT-CS-API-L4-007-02: Delete dependency"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X DELETE "$API_BASE/api/stories/A/dependencies/B" -H "Content-Type: application/json" 2>&1)
DURATION=$((($(date +%s) - START_TIME)))

# Check response
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-CS-API-L4-007-02: Delete dependency"
  PASSED=$((PASSED + 1))
  record_test_result "8" "AT-CS-API-L4-007-02: Delete dependency" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-CS-API-L4-007-02: Delete dependency"
  FAILED=$((FAILED + 1))
  record_test_result "8" "AT-CS-API-L4-007-02: Delete dependency" "FAIL" "$PHASE" "$DURATION"
fi


# Test 10: AT-CS-API-L4-008-02: Get document (Story #1108)
echo "Test 10: AT-CS-API-L4-008-02: Get document"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X GET "$API_BASE/api/documents/789" -H "Content-Type: application/json" 2>&1)
DURATION=$((($(date +%s) - START_TIME)))

# Check response
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-CS-API-L4-008-02: Get document"
  PASSED=$((PASSED + 1))
  record_test_result "10" "AT-CS-API-L4-008-02: Get document" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-CS-API-L4-008-02: Get document"
  FAILED=$((FAILED + 1))
  record_test_result "10" "AT-CS-API-L4-008-02: Get document" "FAIL" "$PHASE" "$DURATION"
fi


# Test 82: AT-OPS-MON-L4-002-01: Version info returned (Story #5102)
echo "Test 82: AT-OPS-MON-L4-002-01: Version info returned"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X GET "$API_BASE/api/version" -H "Content-Type: application/json" 2>&1)
DURATION=$((($(date +%s) - START_TIME)))

# Check response
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-OPS-MON-L4-002-01: Version info returned"
  PASSED=$((PASSED + 1))
  record_test_result "82" "AT-OPS-MON-L4-002-01: Version info returned" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-OPS-MON-L4-002-01: Version info returned"
  FAILED=$((FAILED + 1))
  record_test_result "82" "AT-OPS-MON-L4-002-01: Version info returned" "FAIL" "$PHASE" "$DURATION"
fi


# Test 81: AT-OPS-MON-L4-001-01: Health check returns OK (Story #5101)
echo "Test 81: AT-OPS-MON-L4-001-01: Health check returns OK"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X GET "$API_BASE/health" -H "Content-Type: application/json" 2>&1)
DURATION=$((($(date +%s) - START_TIME)))

# Check response
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-OPS-MON-L4-001-01: Health check returns OK"
  PASSED=$((PASSED + 1))
  record_test_result "81" "AT-OPS-MON-L4-001-01: Health check returns OK" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-OPS-MON-L4-001-01: Health check returns OK"
  FAILED=$((FAILED + 1))
  record_test_result "81" "AT-OPS-MON-L4-001-01: Health check returns OK" "FAIL" "$PHASE" "$DURATION"
fi


# Test 21: AT-CS-API-L4-013-01: Health check (Story #1113)
echo "Test 21: AT-CS-API-L4-013-01: Health check"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X GET "$API_BASE/health" -H "Content-Type: application/json" 2>&1)
DURATION=$((($(date +%s) - START_TIME)))

# Check response
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-CS-API-L4-013-01: Health check"
  PASSED=$((PASSED + 1))
  record_test_result "21" "AT-CS-API-L4-013-01: Health check" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-CS-API-L4-013-01: Health check"
  FAILED=$((FAILED + 1))
  record_test_result "21" "AT-CS-API-L4-013-01: Health check" "FAIL" "$PHASE" "$DURATION"
fi


# Test 18: AT-CS-API-L4-011-02: Get template content (Story #1111)
echo "Test 18: AT-CS-API-L4-011-02: Get template content"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X GET "$API_BASE/api/templates/user-story.md" -H "Content-Type: application/json" 2>&1)
DURATION=$((($(date +%s) - START_TIME)))

# Check response
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-CS-API-L4-011-02: Get template content"
  PASSED=$((PASSED + 1))
  record_test_result "18" "AT-CS-API-L4-011-02: Get template content" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-CS-API-L4-011-02: Get template content"
  FAILED=$((FAILED + 1))
  record_test_result "18" "AT-CS-API-L4-011-02: Get template content" "FAIL" "$PHASE" "$DURATION"
fi


# Test 12: AT-CS-API-L4-009-02: List PRs for story (Story #1109)
echo "Test 12: AT-CS-API-L4-009-02: List PRs for story"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X GET "$API_BASE/api/stories/123/prs" -H "Content-Type: application/json" 2>&1)
DURATION=$((($(date +%s) - START_TIME)))

# Check response
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-CS-API-L4-009-02: List PRs for story"
  PASSED=$((PASSED + 1))
  record_test_result "12" "AT-CS-API-L4-009-02: List PRs for story" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-CS-API-L4-009-02: List PRs for story"
  FAILED=$((FAILED + 1))
  record_test_result "12" "AT-CS-API-L4-009-02: List PRs for story" "FAIL" "$PHASE" "$DURATION"
fi


# Test 4: AT-CS-API-L4-006-02: List tests for story (Story #1106)
echo "Test 4: AT-CS-API-L4-006-02: List tests for story"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X GET "$API_BASE/api/stories/123/tests" -H "Content-Type: application/json" 2>&1)
DURATION=$((($(date +%s) - START_TIME)))

# Check response
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-CS-API-L4-006-02: List tests for story"
  PASSED=$((PASSED + 1))
  record_test_result "4" "AT-CS-API-L4-006-02: List tests for story" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-CS-API-L4-006-02: List tests for story"
  FAILED=$((FAILED + 1))
  record_test_result "4" "AT-CS-API-L4-006-02: List tests for story" "FAIL" "$PHASE" "$DURATION"
fi


# Test 17: AT-CS-API-L4-011-01: List templates (Story #1111)
echo "Test 17: AT-CS-API-L4-011-01: List templates"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X GET "$API_BASE/api/templates" -H "Content-Type: application/json" 2>&1)
DURATION=$((($(date +%s) - START_TIME)))

# Check response
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-CS-API-L4-011-01: List templates"
  PASSED=$((PASSED + 1))
  record_test_result "17" "AT-CS-API-L4-011-01: List templates" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-CS-API-L4-011-01: List templates"
  FAILED=$((FAILED + 1))
  record_test_result "17" "AT-CS-API-L4-011-01: List templates" "FAIL" "$PHASE" "$DURATION"
fi


# Test 6: AT-CS-API-L4-006-04: Delete acceptance test (Story #1106)
echo "Test 6: AT-CS-API-L4-006-04: Delete acceptance test"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X DELETE "$API_BASE/api/tests/456" -H "Content-Type: application/json" 2>&1)
DURATION=$((($(date +%s) - START_TIME)))

# Check response
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-CS-API-L4-006-04: Delete acceptance test"
  PASSED=$((PASSED + 1))
  record_test_result "6" "AT-CS-API-L4-006-04: Delete acceptance test" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-CS-API-L4-006-04: Delete acceptance test"
  FAILED=$((FAILED + 1))
  record_test_result "6" "AT-CS-API-L4-006-04: Delete acceptance test" "FAIL" "$PHASE" "$DURATION"
fi


# Test 5: AT-CS-API-L4-006-03: Update acceptance test (Story #1106)
echo "Test 5: AT-CS-API-L4-006-03: Update acceptance test"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X PUT "$API_BASE/api/tests/456" -H "Content-Type: application/json" 2>&1)
DURATION=$((($(date +%s) - START_TIME)))

# Check response
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-CS-API-L4-006-03: Update acceptance test"
  PASSED=$((PASSED + 1))
  record_test_result "5" "AT-CS-API-L4-006-03: Update acceptance test" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-CS-API-L4-006-03: Update acceptance test"
  FAILED=$((FAILED + 1))
  record_test_result "5" "AT-CS-API-L4-006-03: Update acceptance test" "FAIL" "$PHASE" "$DURATION"
fi


# Test 22: AT-CS-API-L4-013-02: Version info (Story #1113)
echo "Test 22: AT-CS-API-L4-013-02: Version info"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X GET "$API_BASE/api/version" -H "Content-Type: application/json" 2>&1)
DURATION=$((($(date +%s) - START_TIME)))

# Check response
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-CS-API-L4-013-02: Version info"
  PASSED=$((PASSED + 1))
  record_test_result "22" "AT-CS-API-L4-013-02: Version info" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-CS-API-L4-013-02: Version info"
  FAILED=$((FAILED + 1))
  record_test_result "22" "AT-CS-API-L4-013-02: Version info" "FAIL" "$PHASE" "$DURATION"
fi


# Test 24: AT-CS-API-L4-013-04: RTM matrix (Story #1113)
echo "Test 24: AT-CS-API-L4-013-04: RTM matrix"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X GET "$API_BASE/api/rtm/matrix" -H "Content-Type: application/json" 2>&1)
DURATION=$((($(date +%s) - START_TIME)))

# Check response
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-CS-API-L4-013-04: RTM matrix"
  PASSED=$((PASSED + 1))
  record_test_result "24" "AT-CS-API-L4-013-04: RTM matrix" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-CS-API-L4-013-04: RTM matrix"
  FAILED=$((FAILED + 1))
  record_test_result "24" "AT-CS-API-L4-013-04: RTM matrix" "FAIL" "$PHASE" "$DURATION"
fi


# Test 23: AT-CS-API-L4-013-03: Runtime data (Story #1113)
echo "Test 23: AT-CS-API-L4-013-03: Runtime data"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X GET "$API_BASE/api/runtime-data" -H "Content-Type: application/json" 2>&1)
DURATION=$((($(date +%s) - START_TIME)))

# Check response
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-CS-API-L4-013-03: Runtime data"
  PASSED=$((PASSED + 1))
  record_test_result "23" "AT-CS-API-L4-013-03: Runtime data" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-CS-API-L4-013-03: Runtime data"
  FAILED=$((FAILED + 1))
  record_test_result "23" "AT-CS-API-L4-013-03: Runtime data" "FAIL" "$PHASE" "$DURATION"
fi


echo ""
echo "=================================================="
echo "Test Results:"
echo "  Passed: $PASSED"
echo "  Failed: $FAILED"
echo "  Skipped: $SKIPPED"
echo "  Total: $((PASSED + FAILED + SKIPPED))"
echo "=================================================="

if [ $FAILED -gt 0 ]; then
  exit 1
fi

exit 0
