AWSTemplateFormatVersion: '2010-09-09'
Description: 'Kiro Queue Table for async task processing'

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Deployment stage

Resources:
  KiroQueueTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'aipm-kiro-queue-${Stage}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: taskId
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: taskId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: status-createdAt-index
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: Project
          Value: AIPM
        - Key: Stage
          Value: !Ref Stage

Outputs:
  QueueTableName:
    Description: Kiro Queue Table Name
    Value: !Ref KiroQueueTable
    Export:
      Name: !Sub '${AWS::StackName}-QueueTableName'
  
  QueueTableArn:
    Description: Kiro Queue Table ARN
    Value: !GetAtt KiroQueueTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-QueueTableArn'
