#!/bin/bash
# Auto-generated Phase 4 tests from acceptance tests
# DO NOT EDIT MANUALLY - Generated by generate-phase4-from-acceptance-tests.sh

set -e

TEST_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$TEST_SCRIPT_DIR/../utilities/load-env-config.sh" "${TARGET_ENV:-prod}"
source "$TEST_SCRIPT_DIR/test-library.sh"

PASSED=0
FAILED=0
SKIPPED=0
PHASE="phase4-generated"

echo "🧪 Phase 4: Generated Tests from Acceptance Tests"
echo "=================================================="
echo "Run ID: $TEST_RUN_ID"
echo ""


# Test 47: AT-UX-CORE-L5-006-01: Select node (Story #4206) - UI Test
echo "Test 47: AT-UX-CORE-L5-006-01: Select node"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "47" "AT-UX-CORE-L5-006-01: Select node" "SKIP" "$PHASE" "0"


# Test 69: AT-CS-DATA-L4-002-01: Create story in DynamoDB (Story #2102)
echo "Test 69: AT-CS-DATA-L4-002-01: Create story in DynamoDB"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X POST "$API_BASE/api/stories" -H "Content-Type: application/json" -H "X-Use-Dev-Tables: true" -d '{"title":"Test Story","asA":"tester","iWant":"test","soThat":"test","acceptWarnings":true}' 2>&1)
DURATION=$((($(date +%s) - START_TIME)))
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-CS-DATA-L4-002-01: Create story in DynamoDB"
  PASSED=$((PASSED + 1))
  record_test_result "69" "AT-CS-DATA-L4-002-01: Create story in DynamoDB" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-CS-DATA-L4-002-01: Create story in DynamoDB"
  FAILED=$((FAILED + 1))
  record_test_result "69" "AT-CS-DATA-L4-002-01: Create story in DynamoDB" "FAIL" "$PHASE" "$DURATION"
fi


# Test 8: AT-CS-API-L4-007-02: Delete dependency (Story #1107)
echo "Test 8: AT-CS-API-L4-007-02: Delete dependency"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X DELETE "$API_BASE/api/stories/A/dependencies/B" -H "Content-Type: application/json" 2>&1)
DURATION=$((($(date +%s) - START_TIME)))
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-CS-API-L4-007-02: Delete dependency"
  PASSED=$((PASSED + 1))
  record_test_result "8" "AT-CS-API-L4-007-02: Delete dependency" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-CS-API-L4-007-02: Delete dependency"
  FAILED=$((FAILED + 1))
  record_test_result "8" "AT-CS-API-L4-007-02: Delete dependency" "FAIL" "$PHASE" "$DURATION"
fi


# Test 62: AT-UX-INVEST-L4-002-01: Display results (Story #4120) - UI Test
echo "Test 62: AT-UX-INVEST-L4-002-01: Display results"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "62" "AT-UX-INVEST-L4-002-01: Display results" "SKIP" "$PHASE" "0"


# Test 54: AT-UX-TEST-L4-004-01: Confirm test deletion (Story #4112) - UI Test
echo "Test 54: AT-UX-TEST-L4-004-01: Confirm test deletion"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "54" "AT-UX-TEST-L4-004-01: Confirm test deletion" "SKIP" "$PHASE" "0"


# Test 75: AT-CS-DATA-L4-003-03: Update test (Story #2103)
echo "Test 75: AT-CS-DATA-L4-003-03: Update test"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X PUT "$API_BASE/api/acceptance-test" -H "Content-Type: application/json" 2>&1)
DURATION=$((($(date +%s) - START_TIME)))
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-CS-DATA-L4-003-03: Update test"
  PASSED=$((PASSED + 1))
  record_test_result "75" "AT-CS-DATA-L4-003-03: Update test" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-CS-DATA-L4-003-03: Update test"
  FAILED=$((FAILED + 1))
  record_test_result "75" "AT-CS-DATA-L4-003-03: Update test" "FAIL" "$PHASE" "$DURATION"
fi


# Test 32: AT-UX-CORE-L4-002-02: Expand/collapse nodes (Story #4102) - UI Test
echo "Test 32: AT-UX-CORE-L4-002-02: Expand/collapse nodes"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "32" "AT-UX-CORE-L4-002-02: Expand/collapse nodes" "SKIP" "$PHASE" "0"


# Test 56: AT-UX-DEP-L4-002-01: Add dependency (Story #4114) - UI Test
echo "Test 56: AT-UX-DEP-L4-002-01: Add dependency"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "56" "AT-UX-DEP-L4-002-01: Add dependency" "SKIP" "$PHASE" "0"


# Test 1771408421981: Modal closes when user clicks outside or close button (Story #1771408421505) - UI Test
echo "Test 1771408421981: Modal closes when user clicks outside or close button"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "1771408421981" "Modal closes when user clicks outside or close button" "SKIP" "$PHASE" "0"


# Test 39: AT-UX-CORE-L4-006-01: Show confirmation (Story #4106) - UI Test
echo "Test 39: AT-UX-CORE-L4-006-01: Show confirmation"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "39" "AT-UX-CORE-L4-006-01: Show confirmation" "SKIP" "$PHASE" "0"


# Test 10: AT-CS-API-L4-008-02: Get document (Story #1108)
echo "Test 10: AT-CS-API-L4-008-02: Get document"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X GET "$API_BASE/api/documents/789" -H "Content-Type: application/json" 2>&1)
DURATION=$((($(date +%s) - START_TIME)))
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-CS-API-L4-008-02: Get document"
  PASSED=$((PASSED + 1))
  record_test_result "10" "AT-CS-API-L4-008-02: Get document" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-CS-API-L4-008-02: Get document"
  FAILED=$((FAILED + 1))
  record_test_result "10" "AT-CS-API-L4-008-02: Get document" "FAIL" "$PHASE" "$DURATION"
fi


# Test 82: AT-OPS-MON-L4-002-01: Version info returned (Story #5102)
echo "Test 82: AT-OPS-MON-L4-002-01: Version info returned"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X GET "$API_BASE/api/version" -H "Content-Type: application/json" 2>&1)
DURATION=$((($(date +%s) - START_TIME)))
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-OPS-MON-L4-002-01: Version info returned"
  PASSED=$((PASSED + 1))
  record_test_result "82" "AT-OPS-MON-L4-002-01: Version info returned" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-OPS-MON-L4-002-01: Version info returned"
  FAILED=$((FAILED + 1))
  record_test_result "82" "AT-OPS-MON-L4-002-01: Version info returned" "FAIL" "$PHASE" "$DURATION"
fi


# Test 31: AT-UX-CORE-L4-002-01: Display outline (Story #4102) - UI Test
echo "Test 31: AT-UX-CORE-L4-002-01: Display outline"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "31" "AT-UX-CORE-L4-002-01: Display outline" "SKIP" "$PHASE" "0"


# Test 58: AT-UX-GH-L4-001-01: Create PR (Story #4116) - UI Test
echo "Test 58: AT-UX-GH-L4-001-01: Create PR"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "58" "AT-UX-GH-L4-001-01: Create PR" "SKIP" "$PHASE" "0"


# Test 65: AT-UX-UI-L5-001-01: Change status (Story #4208) - UI Test
echo "Test 65: AT-UX-UI-L5-001-01: Change status"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "65" "AT-UX-UI-L5-001-01: Change status" "SKIP" "$PHASE" "0"


# Test 1771408421710: Header button opens modal with story list (Story #1771408421505) - UI Test
echo "Test 1771408421710: Header button opens modal with story list"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "1771408421710" "Header button opens modal with story list" "SKIP" "$PHASE" "0"


# Test 38: AT-UX-CORE-L4-005-02: Save changes (Story #4105) - UI Test
echo "Test 38: AT-UX-CORE-L4-005-02: Save changes"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "38" "AT-UX-CORE-L4-005-02: Save changes" "SKIP" "$PHASE" "0"


# Test 81: AT-OPS-MON-L4-001-01: Health check returns OK (Story #5101)
echo "Test 81: AT-OPS-MON-L4-001-01: Health check returns OK"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X GET "$API_BASE/health" -H "Content-Type: application/json" 2>&1)
DURATION=$((($(date +%s) - START_TIME)))
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-OPS-MON-L4-001-01: Health check returns OK"
  PASSED=$((PASSED + 1))
  record_test_result "81" "AT-OPS-MON-L4-001-01: Health check returns OK" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-OPS-MON-L4-001-01: Health check returns OK"
  FAILED=$((FAILED + 1))
  record_test_result "81" "AT-OPS-MON-L4-001-01: Health check returns OK" "FAIL" "$PHASE" "$DURATION"
fi


# Test 21: AT-CS-API-L4-013-01: Health check (Story #1113)
echo "Test 21: AT-CS-API-L4-013-01: Health check"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X GET "$API_BASE/health" -H "Content-Type: application/json" 2>&1)
DURATION=$((($(date +%s) - START_TIME)))
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-CS-API-L4-013-01: Health check"
  PASSED=$((PASSED + 1))
  record_test_result "21" "AT-CS-API-L4-013-01: Health check" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-CS-API-L4-013-01: Health check"
  FAILED=$((FAILED + 1))
  record_test_result "21" "AT-CS-API-L4-013-01: Health check" "FAIL" "$PHASE" "$DURATION"
fi


# Test 18: AT-CS-API-L4-011-02: Get template content (Story #1111)
echo "Test 18: AT-CS-API-L4-011-02: Get template content"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X GET "$API_BASE/api/templates/user-story.md" -H "Content-Type: application/json" 2>&1)
DURATION=$((($(date +%s) - START_TIME)))
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-CS-API-L4-011-02: Get template content"
  PASSED=$((PASSED + 1))
  record_test_result "18" "AT-CS-API-L4-011-02: Get template content" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-CS-API-L4-011-02: Get template content"
  FAILED=$((FAILED + 1))
  record_test_result "18" "AT-CS-API-L4-011-02: Get template content" "FAIL" "$PHASE" "$DURATION"
fi


# Test 12: AT-CS-API-L4-009-02: List PRs for story (Story #1109)
echo "Test 12: AT-CS-API-L4-009-02: List PRs for story"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X GET "$API_BASE/api/stories/123/prs" -H "Content-Type: application/json" 2>&1)
DURATION=$((($(date +%s) - START_TIME)))
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-CS-API-L4-009-02: List PRs for story"
  PASSED=$((PASSED + 1))
  record_test_result "12" "AT-CS-API-L4-009-02: List PRs for story" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-CS-API-L4-009-02: List PRs for story"
  FAILED=$((FAILED + 1))
  record_test_result "12" "AT-CS-API-L4-009-02: List PRs for story" "FAIL" "$PHASE" "$DURATION"
fi


# Test 53: AT-UX-TEST-L4-003-01: Edit test (Story #4111) - UI Test
echo "Test 53: AT-UX-TEST-L4-003-01: Edit test"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "53" "AT-UX-TEST-L4-003-01: Edit test" "SKIP" "$PHASE" "0"


# Test 4: AT-CS-API-L4-006-02: List tests for story (Story #1106)
echo "Test 4: AT-CS-API-L4-006-02: List tests for story"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X GET "$API_BASE/api/stories/123/tests" -H "Content-Type: application/json" 2>&1)
DURATION=$((($(date +%s) - START_TIME)))
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-CS-API-L4-006-02: List tests for story"
  PASSED=$((PASSED + 1))
  record_test_result "4" "AT-CS-API-L4-006-02: List tests for story" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-CS-API-L4-006-02: List tests for story"
  FAILED=$((FAILED + 1))
  record_test_result "4" "AT-CS-API-L4-006-02: List tests for story" "FAIL" "$PHASE" "$DURATION"
fi


# Test 45: AT-UX-CORE-L5-004-01: Reset zoom (Story #4204) - UI Test
echo "Test 45: AT-UX-CORE-L5-004-01: Reset zoom"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "45" "AT-UX-CORE-L5-004-01: Reset zoom" "SKIP" "$PHASE" "0"


# Test 41: AT-UX-CORE-L5-001-01: Drag node (Story #4201) - UI Test
echo "Test 41: AT-UX-CORE-L5-001-01: Drag node"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "41" "AT-UX-CORE-L5-001-01: Drag node" "SKIP" "$PHASE" "0"


# Test 17: AT-CS-API-L4-011-01: List templates (Story #1111)
echo "Test 17: AT-CS-API-L4-011-01: List templates"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X GET "$API_BASE/api/templates" -H "Content-Type: application/json" 2>&1)
DURATION=$((($(date +%s) - START_TIME)))
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-CS-API-L4-011-01: List templates"
  PASSED=$((PASSED + 1))
  record_test_result "17" "AT-CS-API-L4-011-01: List templates" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-CS-API-L4-011-01: List templates"
  FAILED=$((FAILED + 1))
  record_test_result "17" "AT-CS-API-L4-011-01: List templates" "FAIL" "$PHASE" "$DURATION"
fi


# Test 6: AT-CS-API-L4-006-04: Delete acceptance test (Story #1106)
echo "Test 6: AT-CS-API-L4-006-04: Delete acceptance test"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X DELETE "$API_BASE/api/tests/456" -H "Content-Type: application/json" 2>&1)
DURATION=$((($(date +%s) - START_TIME)))
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-CS-API-L4-006-04: Delete acceptance test"
  PASSED=$((PASSED + 1))
  record_test_result "6" "AT-CS-API-L4-006-04: Delete acceptance test" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-CS-API-L4-006-04: Delete acceptance test"
  FAILED=$((FAILED + 1))
  record_test_result "6" "AT-CS-API-L4-006-04: Delete acceptance test" "FAIL" "$PHASE" "$DURATION"
fi


# Test 66: AT-UX-UI-L5-002-01: Select components (Story #4209) - UI Test
echo "Test 66: AT-UX-UI-L5-002-01: Select components"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "66" "AT-UX-UI-L5-002-01: Select components" "SKIP" "$PHASE" "0"


# Test 63: AT-UX-DOC-L4-001-01: Upload file (Story #4121) - UI Test
echo "Test 63: AT-UX-DOC-L4-001-01: Upload file"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "63" "AT-UX-DOC-L4-001-01: Upload file" "SKIP" "$PHASE" "0"


# Test 50: AT-UX-FILTER-L4-002-01: Search stories (Story #4108) - UI Test
echo "Test 50: AT-UX-FILTER-L4-002-01: Search stories"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "50" "AT-UX-FILTER-L4-002-01: Search stories" "SKIP" "$PHASE" "0"


# Test 36: AT-UX-CORE-L4-004-02: Submit new story (Story #4104) - UI Test
echo "Test 36: AT-UX-CORE-L4-004-02: Submit new story"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "36" "AT-UX-CORE-L4-004-02: Submit new story" "SKIP" "$PHASE" "0"


# Test 71: AT-CS-DATA-L4-002-03: Update story (Story #2102)
echo "Test 71: AT-CS-DATA-L4-002-03: Update story"
START_TIME=$(date +%s)
# Create a test story first, then update it
TEST_STORY=$(curl -s -X POST "$API_BASE/api/stories" -H "Content-Type: application/json" -H "X-Use-Dev-Tables: true" -d '{"title":"Update Test","asA":"tester","iWant":"test","soThat":"test","acceptWarnings":true}')
STORY_ID=$(echo "$TEST_STORY" | jq -r '.id')
if [ "$STORY_ID" != "null" ] && [ -n "$STORY_ID" ]; then
  RESPONSE=$(curl -s -X PUT "$API_BASE/api/stories/$STORY_ID" -H "Content-Type: application/json" -H "X-Use-Dev-Tables: true" -d '{"title":"Updated","asA":"tester","iWant":"test","soThat":"test"}' 2>&1)
  curl -s -X DELETE "$API_BASE/api/stories/$STORY_ID" -H "X-Use-Dev-Tables: true" > /dev/null
else
  RESPONSE=""
fi
DURATION=$((($(date +%s) - START_TIME)))
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status"|"success")'; then
  echo "  ✅ PASS: AT-CS-DATA-L4-002-03: Update story"
  PASSED=$((PASSED + 1))
  record_test_result "71" "AT-CS-DATA-L4-002-03: Update story" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-CS-DATA-L4-002-03: Update story"
  FAILED=$((FAILED + 1))
  record_test_result "71" "AT-CS-DATA-L4-002-03: Update story" "FAIL" "$PHASE" "$DURATION"
fi


# Test 73: AT-CS-DATA-L4-003-01: Create test (Story #2103)
echo "Test 73: AT-CS-DATA-L4-003-01: Create test"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X POST "$API_BASE/api/acceptance-test" -H "Content-Type: application/json" 2>&1)
DURATION=$((($(date +%s) - START_TIME)))
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-CS-DATA-L4-003-01: Create test"
  PASSED=$((PASSED + 1))
  record_test_result "73" "AT-CS-DATA-L4-003-01: Create test" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-CS-DATA-L4-003-01: Create test"
  FAILED=$((FAILED + 1))
  record_test_result "73" "AT-CS-DATA-L4-003-01: Create test" "FAIL" "$PHASE" "$DURATION"
fi


# Test 1771067790825: Filter RTM by status and search by title (Story #1771067790262) - UI Test
echo "Test 1771067790825: Filter RTM by status and search by title"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "1771067790825" "Filter RTM by status and search by title" "SKIP" "$PHASE" "0"


# Test 78: AT-CS-DATA-L5-003-01: Scan all tests (Story #2203)
echo "Test 78: AT-CS-DATA-L5-003-01: Scan all tests"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X GET "$API_BASE/api/all-acceptance-tests" -H "Content-Type: application/json" 2>&1)
DURATION=$((($(date +%s) - START_TIME)))
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-CS-DATA-L5-003-01: Scan all tests"
  PASSED=$((PASSED + 1))
  record_test_result "78" "AT-CS-DATA-L5-003-01: Scan all tests" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-CS-DATA-L5-003-01: Scan all tests"
  FAILED=$((FAILED + 1))
  record_test_result "78" "AT-CS-DATA-L5-003-01: Scan all tests" "FAIL" "$PHASE" "$DURATION"
fi


# Test 61: AT-UX-INVEST-L4-001-01: Run analysis (Story #4119) - UI Test
echo "Test 61: AT-UX-INVEST-L4-001-01: Run analysis"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "61" "AT-UX-INVEST-L4-001-01: Run analysis" "SKIP" "$PHASE" "0"


# Test 1771138996630: AT-RTM-002-01: Click acceptance test shows latest log (Story #1771138996374) - UI Test
echo "Test 1771138996630: AT-RTM-002-01: Click acceptance test shows latest log"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "1771138996630" "AT-RTM-002-01: Click acceptance test shows latest log" "SKIP" "$PHASE" "0"


# Test 34: AT-UX-CORE-L4-003-02: Close detail panel (Story #4103) - UI Test
echo "Test 34: AT-UX-CORE-L4-003-02: Close detail panel"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "34" "AT-UX-CORE-L4-003-02: Close detail panel" "SKIP" "$PHASE" "0"


# Test 42: AT-UX-CORE-L5-002-01: Zoom in (Story #4202) - UI Test
echo "Test 42: AT-UX-CORE-L5-002-01: Zoom in"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "42" "AT-UX-CORE-L5-002-01: Zoom in" "SKIP" "$PHASE" "0"


# Test 77: AT-CS-DATA-L5-002-01: Scan all stories (Story #2202)
echo "Test 77: AT-CS-DATA-L5-002-01: Scan all stories"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X GET "$API_BASE/api/all-stories" -H "Content-Type: application/json" 2>&1)
DURATION=$((($(date +%s) - START_TIME)))
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-CS-DATA-L5-002-01: Scan all stories"
  PASSED=$((PASSED + 1))
  record_test_result "77" "AT-CS-DATA-L5-002-01: Scan all stories" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-CS-DATA-L5-002-01: Scan all stories"
  FAILED=$((FAILED + 1))
  record_test_result "77" "AT-CS-DATA-L5-002-01: Scan all stories" "FAIL" "$PHASE" "$DURATION"
fi


# Test 49: AT-UX-FILTER-L4-001-01: Filter by Done (Story #4107) - UI Test
echo "Test 49: AT-UX-FILTER-L4-001-01: Filter by Done"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "49" "AT-UX-FILTER-L4-001-01: Filter by Done" "SKIP" "$PHASE" "0"


# Test 43: AT-UX-CORE-L5-002-02: Zoom out (Story #4202) - UI Test
echo "Test 43: AT-UX-CORE-L5-002-02: Zoom out"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "43" "AT-UX-CORE-L5-002-02: Zoom out" "SKIP" "$PHASE" "0"


# Test 5: AT-CS-API-L4-006-03: Update acceptance test (Story #1106)
echo "Test 5: AT-CS-API-L4-006-03: Update acceptance test"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X PUT "$API_BASE/api/tests/456" -H "Content-Type: application/json" 2>&1)
DURATION=$((($(date +%s) - START_TIME)))
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-CS-API-L4-006-03: Update acceptance test"
  PASSED=$((PASSED + 1))
  record_test_result "5" "AT-CS-API-L4-006-03: Update acceptance test" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-CS-API-L4-006-03: Update acceptance test"
  FAILED=$((FAILED + 1))
  record_test_result "5" "AT-CS-API-L4-006-03: Update acceptance test" "FAIL" "$PHASE" "$DURATION"
fi


# Test 22: AT-CS-API-L4-013-02: Version info (Story #1113)
echo "Test 22: AT-CS-API-L4-013-02: Version info"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X GET "$API_BASE/api/version" -H "Content-Type: application/json" 2>&1)
DURATION=$((($(date +%s) - START_TIME)))
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-CS-API-L4-013-02: Version info"
  PASSED=$((PASSED + 1))
  record_test_result "22" "AT-CS-API-L4-013-02: Version info" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-CS-API-L4-013-02: Version info"
  FAILED=$((FAILED + 1))
  record_test_result "22" "AT-CS-API-L4-013-02: Version info" "FAIL" "$PHASE" "$DURATION"
fi


# Test 68: AT-UX-UI-L5-004-01: Select parent (Story #4211) - UI Test
echo "Test 68: AT-UX-UI-L5-004-01: Select parent"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "68" "AT-UX-UI-L5-004-01: Select parent" "SKIP" "$PHASE" "0"


# Test 24: AT-CS-API-L4-013-04: RTM matrix (Story #1113)
echo "Test 24: AT-CS-API-L4-013-04: RTM matrix"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X GET "$API_BASE/api/rtm/matrix" -H "Content-Type: application/json" 2>&1)
DURATION=$((($(date +%s) - START_TIME)))
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-CS-API-L4-013-04: RTM matrix"
  PASSED=$((PASSED + 1))
  record_test_result "24" "AT-CS-API-L4-013-04: RTM matrix" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-CS-API-L4-013-04: RTM matrix"
  FAILED=$((FAILED + 1))
  record_test_result "24" "AT-CS-API-L4-013-04: RTM matrix" "FAIL" "$PHASE" "$DURATION"
fi


# Test 23: AT-CS-API-L4-013-03: Runtime data (Story #1113)
echo "Test 23: AT-CS-API-L4-013-03: Runtime data"
START_TIME=$(date +%s)
RESPONSE=$(curl -s -X GET "$API_BASE/api/runtime-data" -H "Content-Type: application/json" 2>&1)
DURATION=$((($(date +%s) - START_TIME)))
if echo "$RESPONSE" | grep -qE '(^\[|^\{|"id"|"status")'; then
  echo "  ✅ PASS: AT-CS-API-L4-013-03: Runtime data"
  PASSED=$((PASSED + 1))
  record_test_result "23" "AT-CS-API-L4-013-03: Runtime data" "PASS" "$PHASE" "$DURATION"
else
  echo "  ❌ FAIL: AT-CS-API-L4-013-03: Runtime data"
  FAILED=$((FAILED + 1))
  record_test_result "23" "AT-CS-API-L4-013-03: Runtime data" "FAIL" "$PHASE" "$DURATION"
fi


# Test 67: AT-UX-UI-L5-003-01: Set story points (Story #4210) - UI Test
echo "Test 67: AT-UX-UI-L5-003-01: Set story points"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "67" "AT-UX-UI-L5-003-01: Set story points" "SKIP" "$PHASE" "0"


# Test 60: AT-UX-GH-L4-003-01: Merge PR (Story #4118) - UI Test
echo "Test 60: AT-UX-GH-L4-003-01: Merge PR"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "60" "AT-UX-GH-L4-003-01: Merge PR" "SKIP" "$PHASE" "0"


# Test 1771076495046: AC-001: Details panel updates on user story click (Story #1771076494719) - UI Test
echo "Test 1771076495046: AC-001: Details panel updates on user story click"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "1771076495046" "AC-001: Details panel updates on user story click" "SKIP" "$PHASE" "0"


# Test 1771656711963: Header button opens modal with story list (Story #1771656711052) - UI Test
echo "Test 1771656711963: Header button opens modal with story list"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "1771656711963" "Header button opens modal with story list" "SKIP" "$PHASE" "0"


# Test 1771656711831: Modal closes when user clicks outside or X button (Story #1771656711052) - UI Test
echo "Test 1771656711831: Modal closes when user clicks outside or X button"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "1771656711831" "Modal closes when user clicks outside or X button" "SKIP" "$PHASE" "0"


# Test 48: AT-UX-CORE-L5-007-01: Collapse children (Story #4207) - UI Test
echo "Test 48: AT-UX-CORE-L5-007-01: Collapse children"
echo "  ⚠️  SKIP: UI test (requires browser automation)"
SKIPPED=$((SKIPPED + 1))
record_test_result "48" "AT-UX-CORE-L5-007-01: Collapse children" "SKIP" "$PHASE" "0"


echo ""
echo "=================================================="
echo "Test Results:"
echo "  Passed: $PASSED"
echo "  Failed: $FAILED"
echo "  Skipped: $SKIPPED"
echo "  Total: $((PASSED + FAILED + SKIPPED))"
echo "=================================================="

if [ $FAILED -gt 0 ]; then
  exit 1
fi

exit 0
