name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm build
      - run: pnpm --filter @ai-pm/backend generate:openapi
      - run: pnpm --filter @ai-pm/frontend e2e
      - run: pnpm --filter @ai-pm/frontend exec npx size-limit
        continue-on-error: true
