name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
        node-version: ['18']
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r apps/backend/requirements.txt

      - name: Run backend tests
        run: pytest apps/backend

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Node dependencies
        run: npm install

      - name: Lint frontend
        run: npm run lint --workspace apps/frontend

      - name: Frontend unit tests
        run: npm run test --workspace apps/frontend -- --run

      - name: Build frontend
        run: npm run build

      - name: Bundle size guard
        run: npm run size --workspace apps/frontend

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Start backend
        run: uvicorn app.main:app --app-dir apps/backend/app --host 0.0.0.0 --port 8000 &

      - name: Start frontend
        run: npm run dev --workspace apps/frontend -- --host 0.0.0.0 --port 5173 &

      - name: Wait for services
        run: npx wait-on http://127.0.0.1:8000/api/health http://127.0.0.1:5173

      - name: Playwright tests
        run: npm run test:e2e --workspace apps/frontend

      - name: Generate OpenAPI
        run: npm run generate:openapi

      - name: Upload OpenAPI artifact
        uses: actions/upload-artifact@v3
        with:
          name: openapi-schema
          path: apps/backend/app/docs/openapi.json
